title: "CakeCollate"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "se-edu/addressbook-level3"
github_icon: "images/Zeke_monke.png"

plugins:
  - jemoji
